Cargo.toml
src/compose/mod.rs
src/compose/test.rs
src/compose/tests/big_shaderdefs/mod.wgsl
src/compose/tests/big_shaderdefs/top.wgsl
src/compose/tests/expected/big_shaderdefs.txt

fix #1 by using a `BitSet` for the module key instead of a `usize`. this dependency is in naga already.
might be a better way to do this that avoids allocating, but it should at least be correct now for larger sets of shader defs.

use BitSet for ModuleKey

---

src/compose/mod.rs
src/compose/test.rs
src/compose/tests/const_in_decl/bind.wgsl
src/compose/tests/const_in_decl/consts.wgsl
src/compose/tests/const_in_decl/top.wgsl
src/compose/tests/expected/import_in_decl.txt

when imported constants are used in headers, rescope them to the current module.
this may have unintended consequences, according to https://www.w3.org/TR/WGSL/#array-types (the example section headed "EXAMPLE: Workgroup variables sized by overridable constants"), workgroup arrays using different but equal `override` source variables for the size will no longer have the same type. 
i'm not sure if there are any significant consequences to that (or even if `override` declarations are actually treated as consts).

rescope imported constants

---

Cargo.toml
examples/pbr_compose_test.rs
src/compose/mod.rs
src/compose/test.rs
src/compose/tests/expected/err_validation_1.txt
src/compose/tests/expected/err_validation_2.txt
src/compose/tests/expected/wgsl_call_entrypoint.txt

update naga to 0.10
update wgpu to 0.14
compose:
- remove `@location`/`@builtin` bindings from demoted entrypoints (this was previously incorrect but not an error)
in tests:
- update expected output
- use `Cow` for passing modules to wgpu.
- require MAPPABLE_PRIMARY_BUFFERS feature for gpu testing

bump naga version

---

Cargo.toml

issue: naga oil requires naga spans to be present but doesn't add the feature.
solution: add the feature, and minor version bump so we can release it.
one of two fixes required for https://github.com/bevyengine/bevy/issues/9028

require span, bump version

---

src/compose/error.rs
src/compose/mod.rs
src/compose/test.rs
src/compose/tests/conditional_import/mod_a.wgsl
src/compose/tests/conditional_import/mod_b.wgsl
src/compose/tests/conditional_import/top.wgsl
src/compose/tests/expected/conditional_import_a.txt
src/compose/tests/expected/conditional_import_b.txt

fixes #27
perform module and item substitution after preprocessing to make sure we use the right imports. 
this is a breaking change as we need to add shader defs into the public `ErrSource::Module` variant, so that errors can be reported with the correct substitutions.

substitute after preprocessing

---

src/compose/comment_strip_iter.rs
src/compose/mod.rs
src/compose/preprocess.rs

adds comment handling to the preprocessor. fixes #34 and lays groundwork for #25. separated out mainly because it is easier to review as a smaller piece and less risky than #25.
luckily glsl and wgsl use the same comment spec

handle comments

---

src/compose/error.rs

don't colorize errors in wasm

---

Cargo.toml
src/compose/mod.rs
src/compose/test.rs
src/compose/tests/expected/dup_import.txt
src/compose/tests/expected/import_in_decl.txt
src/compose/tests/expected/item_import_test.txt
src/compose/tests/expected/use_shared_global.txt
src/compose/tests/use_shared_global/mod.wgsl
src/compose/tests/use_shared_global/top.wgsl
src/compose/util.rs
src/derive.rs
src/prune/mod.rs
src/redirect.rs

fixes #33
this should not merged until bevy 0.11.1 is out. builds on @VitalyAnkh's partial migration, with additionally :
- use `Rc<RefCell>` for `const_expressions` and `const_expr_map` - this is basically unavoidable, as `DerivedModule::import_expression` needs access to both the `const_expressions` and the arena to import into, which may also be `const_expressions`
- don't emit `Expression::Literal` and `Expression::ZeroValue`s
- enforce `const_expression` uniqueness with a custom impl of `PartialEq` for `Expression`s, to ensure that the uniqueness test for globals and consts still passes (else we end up with duplicated items, they no longer test as equal as they refer to different `init` expressions). this could be removed if the `PartialEq` derive on `Expression` in naga is made …

migrate to naga 0.13

---

src/compose/comment_strip_iter.rs

This just removes the unnecessary / invalid escapes.
Addresses #50

Remove no-op regex escapes

---

Cargo.toml

Reduces dependency duplication throughout bevy's dependency tree (other crates use 0.7 while this one uses 0.6)

Update `regex` and `regex-syntax` dependencies

---

.github/workflows/rust.yml
Cargo.toml
src/compose/error.rs
src/compose/mod.rs
src/compose/test.rs

This can be used to reduce the final binary size when a consumer only needs WGSL support. I've enabled the feature by default for backwards-compatibility

Add 'glsl' feature to gate naga glsl features

---

src/compose/mod.rs

the `undecorate_regex` captures part of the ansi color codes and eats them in error reports. 
updated the regex to exclude ansi codes from matched names.
fixes #64

fix errors color coding

---

src/compose/preprocess.rs

error span offsets are incorrectly reported with preceding multi-line imports. 
add a "\n" for each multiline import to get the correct source location.

add newline in import loop to fix error locations

---

src/compose/preprocess.rs

fixes bevyengine/bevy#10533
shader defs used only in literal substitutions (`#MY_DEF` or `#{MY_DEF}`) were not counted towards the module's effective defs, so were not validated when looking for an existing cached version of the module.
add them to effective defs.

non-scope defs are effective

---

Cargo.toml
examples/pbr_compose_test.rs
src/compose/mod.rs
src/compose/test.rs
src/compose/tests/expected/additional_import.txt
src/compose/tests/expected/bad_identifiers.txt
src/compose/tests/expected/big_shaderdefs.txt
src/compose/tests/expected/dup_import.txt
src/compose/tests/expected/dup_struct_import.txt
src/compose/tests/expected/glsl_call_wgsl.txt
src/compose/tests/expected/glsl_const_import.txt
src/compose/tests/expected/glsl_wgsl_const_import.txt
src/compose/tests/expected/item_sub_point.txt
src/compose/tests/expected/simple_compose.txt
src/compose/tests/expected/test_quoted_import_dup_name.txt
src/compose/tests/expected/use_shared_global.txt
src/compose/tests/expected/wgsl_call_entrypoint.txt
src/compose/tests/expected/wgsl_glsl_const_import.txt
src/prune/mod.rs

~~It comes out on the 17th hopefully, so opening this now to hopefully get an easy update. Will undraft on release,~~
Also sneakily includes a fix for a new version of `cargo fmt` that came out since the last time it was ran on this project.
Tests work on my machine (windows) but CI fails on Ubuntu for... unknown reasons. I don't think it's related to this PR.

Update to Naga 0.19

---

Cargo.toml
src/compose/mod.rs
src/compose/parse_imports.rs
src/compose/preprocess.rs
src/compose/test.rs
src/compose/tests/expected/bad_identifiers.txt
src/compose/tests/expected/dup_import.txt
src/compose/tests/expected/dup_struct_import.txt
src/compose/tests/expected/item_import_test.txt
src/compose/tests/expected/wgsl_call_glsl.txt
src/derive.rs

fix OS-level shader caching by switching to `IndexMap` to maintain naga's deterministic output.

Deterministic output

---

Cargo.toml
src/compose/error.rs
src/compose/mod.rs
src/compose/preprocess.rs
src/compose/test.rs
src/compose/tests/expected/err_validation_1.txt
src/compose/tests/expected/err_validation_2.txt
src/derive.rs

This currently doesn't pass the tests, I think because `naga` removed the `PartialEq` implementation on a bunch of types (https://github.com/gfx-rs/wgpu/pull/5818)

Upgrade to WGPU 22

---

src/compose/error.rs

I ran accross a case where instead of a warning I got an unwrap in error handling. Two cases didn't seem to use `unwrap_or(0..0)` like all the others in this function. The errors will get slightly weird when it's missing but at least it won't cause crashes and the user has some idea of what is wrong

Replace unwrap in error handling

---

src/compose/comment_strip_iter.rs

fixes #81
ignore comment markers in `"` quotes (unless the quote is already in a comment).
also fix `*/` incorrectly stripping the marker and returning `  `, and `/* //*` failing to recognise the second block start marker (thanks @stefnotch for the tests).

don't strip quoted comments

---

src/compose/error.rs

Detect if terminal supports ANSI

---

src/compose/mod.rs
src/compose/test.rs
src/compose/tests/conditional_import_fail/middle.wgsl
src/compose/tests/conditional_import_fail/mod_a_b.wgsl
src/compose/tests/conditional_import_fail/top.wgsl
src/compose/tests/conditional_import_fail/top_nested.wgsl
src/compose/tests/expected/conditional_missing_import.txt
src/compose/tests/expected/conditional_missing_import_nested.txt

If an import is missing from the module it currently just unwraps and panics without any explanations.
Don't unwrap and bubble up the error instead.
The error reporting is a bit weird because it just points at the start of the file and I'm not sure how to improve it.

Report missing import error

---

src/derive.rs

For some reason wgpu-25 becomes very grumpy with this otherwise:
```sh
called `Result::unwrap()` on an `Err` value: BadHandle { kind: "naga::ir::Expression", index: 16 }
```

Fix attempt to import offset as const.

---

Cargo.toml
src/compose/comment_strip_iter.rs
src/compose/mod.rs

There are a few dependencies that are no longer necessary due to the MSRV at 1.84. Also removed the `regex-syntax` dependency since this crate already pulls in the entire `regex` crate.

Dependency cleanup
